import type { Entry, Stage } from "./types.ts";
import { countByCountry, countryShares, investmentUsdByCountry } from "./aggregate.ts";
import { entriesAsOf, daysAgo } from "./history.ts";
import { countryName } from "./countries.ts";
import { fmtUsd } from "./format.ts";
import type { Dashboard } from "./urlState.ts";

const CHANGE_WINDOW_DAYS = 42;

export interface DashboardSummaryCard {
  dashboard: Dashboard;
  label: string;
  country: string | null;
  countryLabel: string;
  value: string;
  leaderSharePct: number;
  runnerUp: string | null;
  runnerUpLabel: string | null;
  runnerUpSharePct: number | null;
  gapPct: number | null;
  changeLabel: string | null;
  period: string;
  definition: string;
  interpretation: string;
}

const CARD_META: { dashboard: Dashboard; label: string; stage: Stage; definition: string; byDollar?: boolean }[] = [
  { dashboard: "research", label: "Research", stage: "innovation", definition: "Share of tracked papers, patents, and research statistics." },
  { dashboard: "scaling", label: "Scaling", stage: "scaling", definition: "Share of tracked hardware and production milestones." },
  { dashboard: "adoption", label: "Adoption", stage: "adoption", definition: "Share of tracked deployment and procurement records." },
  { dashboard: "money", label: "Money", stage: "investment", definition: "Share of real disclosed dollars — NSF grants + disclosed private funding rounds — US/EU-weighted, no comparable China feed.", byDollar: true },
];

// One real leader-country card per dashboard — never mixes "fastest riser"/
// "largest lead"/"most concentrated" framings without saying which stage
// and measure each refers to. Research/Scaling/Adoption rank countries by
// tracked-entry share (a paper/milestone/adoption record are all roughly
// comparable "one unit"). Money ranks by real disclosed DOLLAR share
// instead (see investmentUsdByCountry in aggregate.ts) — entry count would
// let NSF's much larger number of smaller grants swamp a country with one
// real, large, disclosed private round, understating it (confirmed by
// hand: a country with one real, large private round rounded to 0% "share"
// by entry count despite carrying a meaningful real dollar share).
// Returns null for a card when there's no real leader yet, rather than
// padding.
export function computeDashboardSummaryCards(entries: Entry[], now = new Date()): DashboardSummaryCard[] {
  const past = entriesAsOf(entries, daysAgo(CHANGE_WINDOW_DAYS, now));
  const hasHistory = past.length > 0;

  const raw: DashboardSummaryCard[] = [];
  for (const meta of CARD_META) {
    const rankBasis = meta.byDollar ? investmentUsdByCountry(entries) : countByCountry(entries, meta.stage);
    const entryCounts = countByCountry(entries, meta.stage);
    const ranked = Object.entries(rankBasis).sort((a, b) => b[1] - a[1]);
    if (ranked.length === 0) continue;
    const [leader] = ranked[0];
    const leaderCount = entryCounts[leader] ?? 0;
    const shares = countryShares(rankBasis);
    const leaderShare = shares[leader] ?? 0;
    const runnerUpEntry = ranked[1] ?? null;
    const runnerUpShare = runnerUpEntry ? (shares[runnerUpEntry[0]] ?? 0) : null;
    const gap = runnerUpShare != null ? leaderShare - runnerUpShare : null;
    let changeLabel: string | null = null;
    if (hasHistory) {
      const pastRankBasis = meta.byDollar ? investmentUsdByCountry(past) : countByCountry(past, meta.stage);
      const pastShares = countryShares(pastRankBasis);
      const delta = leaderShare - (pastShares[leader] ?? 0);
      if (Math.abs(delta) >= 0.5) changeLabel = `${delta > 0 ? "+" : "−"}${Math.abs(delta).toFixed(1)} percentage points over ${CHANGE_WINDOW_DAYS} days`;
    }
    const value = meta.byDollar
      ? `${leaderShare.toFixed(0)}% of tracked disclosed dollars (${fmtUsd(rankBasis[leader] ?? 0)}, ${leaderCount} record${leaderCount === 1 ? "" : "s"})`
      : `${leaderShare.toFixed(0)}% of tracked ${meta.label.toLowerCase()} output (${leaderCount} entries)`;
    raw.push({
      dashboard: meta.dashboard,
      label: meta.label,
      country: leader,
      countryLabel: countryName(leader),
      value,
      leaderSharePct: leaderShare,
      runnerUp: runnerUpEntry?.[0] ?? null,
      runnerUpLabel: runnerUpEntry ? countryName(runnerUpEntry[0]) : null,
      runnerUpSharePct: runnerUpShare,
      gapPct: gap,
      changeLabel,
      period: `as of the latest build`,
      definition: meta.definition,
      interpretation: "",
    });
  }

  // "One short interpretation" per card — generated by comparing this
  // dashboard's leader-to-runner-up gap against the average gap across the
  // OTHER tracked dashboards, never a hardcoded claim. Needs at least 2
  // cards with a real gap to say anything comparative; otherwise the card
  // just states its own number with no cross-dashboard claim.
  const withGap = raw.filter((c) => c.gapPct != null);
  for (const card of raw) {
    if (card.gapPct == null || withGap.length < 2) {
      card.interpretation = `${card.countryLabel} leads ${card.label.toLowerCase()} with no directly comparable runner-up yet.`;
      continue;
    }
    const others = withGap.filter((c) => c.dashboard !== card.dashboard);
    if (others.length === 0) {
      card.interpretation = `${card.countryLabel}'s lead is ${card.gapPct.toFixed(0)} percentage points over ${card.runnerUpLabel}.`;
      continue;
    }
    const avgOtherGap = others.reduce((s, c) => s + (c.gapPct ?? 0), 0) / others.length;
    const otherLabels = others.map((c) => c.label.toLowerCase()).join("/");
    if (card.gapPct > avgOtherGap * 1.15) {
      card.interpretation = `${card.label} leadership is more concentrated than ${otherLabels} leadership.`;
    } else if (card.gapPct < avgOtherGap * 0.85) {
      card.interpretation = `${card.label} leadership is less concentrated than ${otherLabels} leadership.`;
    } else {
      card.interpretation = `${card.label} leadership is about as concentrated as ${otherLabels} leadership.`;
    }
  }

  return raw;
}
