/**
 * Regenerates src/lib/continentMap.ts from the world-countries package.
 *
 * world-countries carries every field (names in a dozen languages, borders,
 * currencies, flags...) for 250 countries — importing the whole package into
 * the CLIENT bundle (as countries.ts used to) cost >250KB of dead weight for
 * a single field. This script runs once in Node, in the same spirit as
 * scripts/backfill-trend.ts, and writes out just the alpha-2 -> continent
 * pairs the app actually needs as a small static object literal. Rerun this
 * only if `npm update world-countries` changes the ISO country list (rare —
 * it doesn't need to be part of the regular build).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import worldCountries from "world-countries";
import type { Continent } from "../src/lib/countries.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/lib/continentMap.ts");

const map: Record<string, Continent> = {};
for (const c of worldCountries as Array<{ cca2: string; region: string; subregion: string }>) {
  if (c.region === "Americas") map[c.cca2] = c.subregion === "South America" ? "south-america" : "north-america";
  else if (c.region === "Europe") map[c.cca2] = "europe";
  else if (c.region === "Asia") map[c.cca2] = "asia";
  else if (c.region === "Africa") map[c.cca2] = "africa";
  else if (c.region === "Oceania") map[c.cca2] = "oceania";
}

// world-countries has no Middle East region of its own — it folds those
// countries into Asia (Egypt into Africa). country.json (hand-supplied,
// 2026-07-19) carries an explicit Middle East bucket, so those specific
// codes are overridden after the world-countries base pass rather than left
// on whatever world-countries called them. Everything else stays on the
// generated, not-hand-maintained, base — this is a one-region carve-out,
// not a switch to a fully hand-maintained table.
const countryInfo = JSON.parse(readFileSync(resolve(__dirname, "../country.json"), "utf-8")).country_info as Record<
  string,
  [string, string]
>;
for (const [code, [, region]] of Object.entries(countryInfo)) {
  if (region === "Middle East") map[code] = "middle-east";
}

const body =
  `// Generated by scripts/gen-continent-map.ts from the world-countries package —\n` +
  `// do not hand-edit. Rerun the script to regenerate if the ISO country list changes.\n` +
  `import type { Continent } from "./countries.ts";\n\n` +
  `export const CONTINENT_BY_CODE: Record<string, Continent> = ${JSON.stringify(map, Object.keys(map).sort(), 2)};\n`;

writeFileSync(OUT, body);
console.log(`wrote ${Object.keys(map).length} country->continent entries -> ${OUT}`);
